import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import type { Locale } from '@/i18n/config'
import { i18n } from '@/i18n/config'
import { isLocale } from '@/i18n/utils'
import { getDictionary } from '@/lib/getDictionary'
import { I18nProvider } from '@/contexts/i18nContext'
import '@/styles/globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: '/favicon.ico',
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: string }
}) {
  const validLang: Locale = isLocale(params.lang)
    ? params.lang
    : i18n.defaultLocale
  const dictionary = await getDictionary(validLang)

  return (
    <I18nProvider dictionary={dictionary}>
      <html lang={validLang}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </I18nProvider>
  )
}
